/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'decks',
    path: '/decks',
    component: 'layout.base$view.decks',
    meta: {
      title: 'decks',
      i18nKey: 'route.decks',
      icon: 'mdi:format-list-group',
      order: 3,
      roles: ['0']
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      roles: ['1'],
      order: 3,
      icon: 'mdi:user'
    },
    children: [
    {
        name: 'user_facts',
        path: '/user/facts',
        component: 'view.user_facts',
        meta: {
          keepAlive: true,
          title: 'user_facts_facts',
          i18nKey: 'route.user_facts',
          order: 3,
          icon: 'mdi:lightbulb',
          roles: ['1']
        }
      },
      {
        name: 'user_cards',
        path: '/user/cards',
        component: 'view.user_cards',
        meta: {
          keepAlive: true,
          title: 'user_cards',
          i18nKey: 'route.user_cards',
          order: 2,
          icon: 'mdi:cards',
          roles: ['1']
        }
      },
      {
        name: 'user_decks',
        path: '/user/decks',
        component: 'view.user_decks',
        meta: {
          title: 'user_decks',
          i18nKey: 'route.user_decks',
          order: 1,
          icon: 'mdi:format-list-group',
          roles: ['1']
        }
      }
    ]
  },
  {
    name: 'users',
    path: '/users',
    component: 'layout.base$view.users',
    meta: {
      title: 'users',
      i18nKey: 'route.users',
      icon: 'mdi:user',
      order: 2,
      roles: ['0']
    }
  }
];
