/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'cards',
    path: '/cards',
    component: 'layout.base$view.cards',
    meta: {
      title: 'cards',
      i18nKey: 'route.cards',
      order: 4,
      icon: 'mdi:cards'
    }
  },
  {
    name: 'decks',
    path: '/decks',
    component: 'layout.base$view.decks',
    meta: {
      title: 'decks',
      i18nKey: 'route.decks',
      icon: 'mdi:format-list-group',
      order: 3
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'users',
    path: '/users',
    component: 'layout.base$view.users',
    meta: {
      title: 'users',
      i18nKey: 'route.users',
      icon: 'mdi:user',
      order: 2
    }
  }
];
